In [1]:
import numpy as np

In [2]:
# 1차원 배열 생성
x1 = np.array([1.0,2.0,3.0])
x2 = np.array([5.0,10.0,15.0])
print(x1,x2)
print(type(x1),type(x2))

[1. 2. 3.] [ 5. 10. 15.]
<class 'numpy.ndarray'> <class 'numpy.ndarray'>


In [3]:
# 2차원 배열 생성
y1 = np.array([[1.0,2.0],[3.0,4.0]])
y2 = np.array([[5.0,10.0],[15.0,20.0]])
print(y1); print()
print(y2)
print(type(y1),type(y2))

[[1. 2.]
 [3. 4.]]

[[ 5. 10.]
 [15. 20.]]
<class 'numpy.ndarray'> <class 'numpy.ndarray'>


In [4]:
# numpy 원소에 접근 : x1[0] -> 1.0
print(x1[0])
print(y1[0][0])

1.0
1.0


In [5]:
# 리스트를 넘파이 배열로
a_list = [1.0,2.0,3.0]
a_np = np.array(a_list)
print(type(a_list),type(a_np))

<class 'list'> <class 'numpy.ndarray'>


In [23]:
a = np.arange(20) # 0~14까지
print(a.ndim)
print(a.shape)
print(a.size)
print(a)
a = a.reshape(4,5) #  3행 5열로 만들어 넣는다.
print(a.ndim)
print(a.shape)
print(a.size)
print(a)
a = np.arange(20).reshape(2,2,5)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.dtype.name)
print(a.dtype.itemsize)
print(a)
a = np.arange(-5,5,0.5).reshape(4,5)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.dtype.name)
print(a.dtype.itemsize)
print(a)

1
(20,)
20
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
2
(4, 5)
20
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
3
(2, 2, 5)
20
int32
int32
4
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]]
2
(4, 5)
20
float64
float64
8
[[-5.  -4.5 -4.  -3.5 -3. ]
 [-2.5 -2.  -1.5 -1.  -0.5]
 [ 0.   0.5  1.   1.5  2. ]
 [ 2.5  3.   3.5  4.   4.5]]


In [7]:
# 빈 배열 생성
arr = np.empty((4,3)) # 4 by 3 인 배열 생성 -> 메모리에 있던 값이 들어옴.
print(arr)

# 초기값을 부여하면서 array 생성
# 초기값 0
arr = np.zeros(5) # 1차원 배열 5행인 배열 -> 초기값 0
print(arr); print()
arr = np.zeros((2,3))
print(arr); print()

# 초기값 1
arr = np.ones((3,4) , dtype='i8') # dtype = 'i' 정수로, 'f' : 실수, 'U' : 문자
print(arr)
print(arr.dtype, arr.dtype.itemsize)

# 기존 배열 초기화시키기
arr = np.ones_like(arr, dtype='f')
print(arr)
print(arr.dtype, arr.dtype.itemsize)
print()

arr = np.zeros_like(arr, dtype='U')
print(arr)
print(arr.dtype, arr.dtype.itemsize)

[[6.14400189e-312 3.16202013e-322 0.00000000e+000]
 [0.00000000e+000 6.13256784e-312 1.86386255e+160]
 [1.24561317e-047 1.08555006e-042 3.53802044e-057]
 [6.12390379e-062 1.86924533e-051 6.23194112e+174]]
[0. 0. 0. 0. 0.]

[[0. 0. 0.]
 [0. 0. 0.]]

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
int64 8
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
float32 4

[['' '' '' '']
 ['' '' '' '']
 ['' '' '' '']]
<U1 4


In [19]:
# array 연산
x1 = np.array([1.0,2.0,3.0])
y1 = np.array([5.0,10.0,15.0])
x2 = np.array([[1.0,2.0],[3.0,4.0]])
y2 = np.array([[5.0,10.0],[15.0,20.0]])
z1 = np.array([-1.0,-2.0])
z2 = np.array([[5.0],[10.0],[15.0]])

print("x1과 y1")
print(x1 + y1); print()
print(x1 - y1); print()
print(x1 * y1); print()
print(x1 / y1); print()
print("x2과 y2")
print(x2 + y2); print()
print(x2 - y2); print()
print(x2 * y2); print()
print(x2 / y2); print()
print("x2과 z1")
print(x2 + z1); print()
print(x2 - z1); print()
print(x2 * z1); print()
print(x2 / z1); print()
print("x1과 z2")
print(x1 + z2); print()
print(x1 - z2); print()
print(x1 * z2); print()
print(x1 / z2); print()

x1과 y1
[ 6. 12. 18.]

[ -4.  -8. -12.]

[ 5. 20. 45.]

[0.2 0.2 0.2]

x2과 y2
[[ 6. 12.]
 [18. 24.]]

[[ -4.  -8.]
 [-12. -16.]]

[[ 5. 20.]
 [45. 80.]]

[[0.2 0.2]
 [0.2 0.2]]

x2과 z1
[[0. 0.]
 [2. 2.]]

[[2. 4.]
 [4. 6.]]

[[-1. -4.]
 [-3. -8.]]

[[-1. -1.]
 [-3. -2.]]

x1과 z2
[[ 6.  7.  8.]
 [11. 12. 13.]
 [16. 17. 18.]]

[[ -4.  -3.  -2.]
 [ -9.  -8.  -7.]
 [-14. -13. -12.]]

[[ 5. 10. 15.]
 [10. 20. 30.]
 [15. 30. 45.]]

[[0.2        0.4        0.6       ]
 [0.1        0.2        0.3       ]
 [0.06666667 0.13333333 0.2       ]]



In [21]:
x1 = np.array([1.0,2.0,3.0])
y1 = np.array([5.0,10.0,15.0])
x2 = np.array([[1.0,2.0],[3.0,4.0]])
y2 = np.array([[5.0,10.0],[15.0,20.0]])
z1 = np.array([-1.0,-2.0])
z2 = np.array([[5.0],[10.0],[15.0]])

print(x1@z2)
print(np.dot(z1,x2))
print(z1.dot(y2))

[70.]
[ -7. -10.]
[-35. -50.]


In [9]:
# 배열의 형 변환 ***
print(z2); print()
print(z2.flatten()) # 평탄화 시킴 : 모든 차수의 배열을 1차원으로

[[ 5.]
 [10.]
 [15.]]

[ 5. 10. 15.]


In [33]:
# array인덱싱, 슬라이싱, 반복
a = np.arange(10)**2
print(a)
print(a[3:5])
print(a[2])
print(a[::-1])
print(a[0:6:2])
a[0:6:2] = -a[0:6:2]
print(a)

[ 0  1  4  9 16 25 36 49 64 81]
[ 9 16]
4
[81 64 49 36 25 16  9  4  1  0]
[ 0  4 16]
[  0   1  -4   9 -16  25  36  49  64  81]


In [34]:
# 반복문
a = np.arange(10)**2
for x in a:
    print(x+1, end=' ')

print()
x2 = np.array([[1.0,2.0],[3.0,4.0]])
for x in x2:
    print(x+1)    

1 2 -3 10 -15 26 37 50 65 82 
[2. 3.]
[4. 5.]


In [29]:
a = np.arange(1,21,1).reshape(4,5)
print(a); print()
print(a[2,1]); print()
print(a[:2,]); print()
print(a[1,]); print()
print(a[:,-1]); print()
print(a[:,-1].shape); print()
print(a[:,3:])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

12

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

[ 6  7  8  9 10]

[ 5 10 15 20]

(4,)

[[ 4  5]
 [ 9 10]
 [14 15]
 [19 20]]


In [45]:
# numpy의 함수
a = np.arange(1, 6, 1)
print(a)
print(np.sin(a))
print(np.sin(a).round(3))
print(np.cos(a).round(3))
print(np.tanh(a).round(3))
print(np.exp(a).round(3))
print(np.log(a).round(3))

[1 2 3 4 5]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[ 0.841  0.909  0.141 -0.757 -0.959]
[ 0.54  -0.416 -0.99  -0.654  0.284]
[0.762 0.964 0.995 0.999 1.   ]
[  2.718   7.389  20.086  54.598 148.413]
[0.    0.693 1.099 1.386 1.609]


In [49]:
a1 = np.array([7,8,9,10])
a2 = np.array([1,5,10,20])
print(np.maximum(a1,a2))
print(np.minimum(a1,a2))
print(np.sum(a1))

[ 7  8 10 20]
[ 1  5  9 10]
34


In [55]:
# 데이터의 개수(count)
# 평균(mean, average)
# 분산(variance)
# 표준 편차(standard deviation)
# 최댓값(maximum)
# 최솟값(minimum)
# 중앙값(median)
# 사분위수(quartile)

x = np.array([18,   5,  10,  23,  19,  -8,  10,   0,   0,   5,   2,  15,   8,
              2,   5,   4,  15,  -1,   4,  -7, -24,   7,   9,  -6,  23, -13])
print(len(x))  # 갯수
print(np.mean(x))  # 평균
print(np.var(x))  # 분산
print(np.std(x))  # 표준 편차
print(np.max(x))  # 최대값
print(np.min(x))  # 최소값
print(np.median(x))  # 중앙값
print(np.percentile(x, 0)) # 최소값
print(np.percentile(x, 25)) # 1사분위 수
print(np.percentile(x, 50)) # 중앙값
print(np.percentile(x, 75)) # 3사분위 수
print(np.percentile(x, 100))  # 최대값

26
4.8076923076923075
115.23224852071006
10.734628476137871
23
-24
5.0
-24.0
0.0
5.0
10.0
23.0


In [68]:
np.random.seed(0)  # 시작 숫자를 정해 주면 항상 같은 숫자의 난수 발생
print(np.random.rand(5))  # 난수 5개 발생
print(np.random.randn(5))

[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548 ]
[-0.84272405  1.96992445  1.26611853 -0.50587654  2.54520078]


In [106]:
print(np.random.randint(10))
print(np.random.randint(10, size=1))
print(np.random.randint(10, size=5))
print(np.random.randint(10, 20, size=5))
print(np.random.randint(10, 20, size=(3, 5)))

5
[4]
[1 5 8 3 5]
[18 14 11 17 18]
[[11 12 11 11 17]
 [15 10 14 11 11]
 [16 16 10 12 13]]


In [82]:
x = np.arange(10)
print(x)
np.random.shuffle(x)  # 데이터 순서 바꿈
print(x)

[0 1 2 3 4 5 6 7 8 9]
[5 7 4 3 6 9 0 8 2 1]


In [104]:
print(type(np.random.choice(5,1, replace=False)))  # shuffle 명령과 같다.
print(np.random.choice(x, len(x), replace=False))
# 
print(np.random.choice(5, 3, replace=False))  # 중복x, 3개만 선택
# 
print(np.random.choice(5, 10))  # 중복허용, 10개 선택
# 
print(np.random.choice(5, 10, p=[0.1, 0, 0.3, 0.6, 0]))  # 선택 확률을 다르게 해서 10개 선택
# 

<class 'numpy.ndarray'>
[8 6 4 5 7 1 2 3 9 0]
[0 2 1]
[3 2 0 1 0 1 1 4 2 2]
[2 2 3 2 3 3 3 3 2 3]


In [95]:
def y():
    pass
print(y)

<function y at 0x000001218C1024C0>


In [51]:
a = np.array([6,10,3,2,4,5])
print(np.argmax(a)) # 가장 큰 값의 인덱스 반환
print(a[np.argmax(a)])
print(np.argmin(a)) # 가장 작은 값의 인덱스 반환
print(a[np.argmin(a)])
print()

a = np.array([[1,8,2],[3,2,5],[9,5,3]])
print(np.argmax(a))
print(np.argmax(a,axis=0))
print(np.argmax(a,axis=1))

1
10
3
2

6
[2 0 1]
[1 2 0]


In [17]:
np.random.seed(0) # 시드값을 넣어주면 매 실행마다 값이 바뀌지 않는다.
print(np.random.rand(5))

[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548 ]


In [18]:
x = np.arange(1,21)
print(x)
print(x[x%3==0])
print(x[x%4==1])
print(x[(x%3==0) & (x%4==1)])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 3  6  9 12 15 18]
[ 1  5  9 13 17]
[9]
