In [2]:
import numpy as np

In [2]:
# 1차원 배열 생성
x1 = np.array([1.0,2.0,3.0])
x2 = np.array([5.0,10.0,15.0])
print(x1,x2)
print(type(x1),type(x2))

[1. 2. 3.] [ 5. 10. 15.]
<class 'numpy.ndarray'> <class 'numpy.ndarray'>


In [5]:
# 2차원 배열 생성
y1 = np.array([[1.0,2.0],[3.0,4.0]])
y2 = np.array([[5.0,10.0],[15.0,20.0]])
print(y1); print()
print(y2)
print(type(y1),type(y2))

[[1. 2.]
 [3. 4.]]

[[ 5. 10.]
 [15. 20.]]
<class 'numpy.ndarray'> <class 'numpy.ndarray'>


In [6]:
# numpy 원소에 접근 : x1[0] -> 1.0
print(x1[0])
print(y1[0][0])

1.0
1.0


In [7]:
# 리스트를 넘파이 배열로
a_list = [1.0,2.0,3.0]
a_np = np.array(a_list)
print(type(a_list),type(a_np))

<class 'list'> <class 'numpy.ndarray'>


In [19]:
a = np.arange(15) # 0~14까지
print(a.ndim)
print(a.shape)
print(a.size)
print()
a = a.reshape(3,5) #  3행 5열로 만들어 넣는다.
print(a.ndim)
print(a.shape)
print(a.size)
print()
a = np.arange(20).reshape(2,2,5)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.dtype.name)
print(a.dtype.itemsize)
print()
a = np.arange(-5,5,0.5).reshape(4,5)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.dtype.name)
print(a.dtype.itemsize)
print()

1
(15,)
15

2
(3, 5)
15

3
(2, 2, 5)
20
int32
int32
4

2
(4, 5)
20
float64
float64
8



In [33]:
# 빈 배열 생성
arr = np.empty((4,3)) # 4 by 3 인 배열 생성 -> 메모리에 있던 값이 들어옴.
print(arr)

# 초기값을 부여하면서 array 생성
# 초기값 0
arr = np.zeros(5) # 1차원 배열 5행인 배열 -> 초기값 0
print(arr); print()
arr = np.zeros((2,3))
print(arr); print()

# 초기값 1
arr = np.ones((3,4) , dtype='i8') # dtype = 'i' 정수로, 'f' : 실수, 'U' : 문자
print(arr)
print(arr.dtype, arr.dtype.itemsize)

# 기존 배열 초기화시키기
arr = np.ones_like(arr, dtype='f')
print(arr)
print(arr.dtype, arr.dtype.itemsize)
print()

arr = np.zeros_like(arr, dtype='U')
print(arr)
print(arr.dtype, arr.dtype.itemsize)

[[5.e-324 5.e-324 5.e-324]
 [5.e-324 5.e-324 5.e-324]
 [5.e-324 5.e-324 5.e-324]
 [5.e-324 5.e-324 5.e-324]]
[0. 0. 0. 0. 0.]

[[0. 0. 0.]
 [0. 0. 0.]]

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
int64 8
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
float32 4

[['' '' '' '']
 ['' '' '' '']
 ['' '' '' '']]
<U1 4


In [37]:
# array 연사
x1 = np.array([1.0,2.0,3.0])
y1 = np.array([5.0,10.0,15.0])
x2 = np.array([[1.0,2.0],[3.0,4.0]])
y2 = np.array([[5.0,10.0],[15.0,20.0]])
z1 = np.array([-1.0,-2.0])
z2 = np.array([[5.0],[10.0],[15.0]])

print("x1과 y1")
print(x1 + y1); print()
print(x1 - y1); print()
print(x1 * y1); print()
print(x1 / y1); print()
print("x2과 y2")
print(x2 + y2); print()
print(x2 - y2); print()
print(x2 * y2); print()
print(x2 / y2); print()
print("x2과 z1")
print(x2 + z1); print()
print(x2 - z1); print()
print(x2 * z1); print()
print(x2 / z1); print()

x1과 y1
[ 6. 12. 18.]

[ -4.  -8. -12.]

[ 5. 20. 45.]

[0.2 0.2 0.2]

x2과 y2
[[ 6. 12.]
 [18. 24.]]

[[ -4.  -8.]
 [-12. -16.]]

[[ 5. 20.]
 [45. 80.]]

[[0.2 0.2]
 [0.2 0.2]]

x2과 z1
[[0. 0.]
 [2. 2.]]

[[2. 4.]
 [4. 6.]]

[[-1. -4.]
 [-3. -8.]]

[[-1. -1.]
 [-3. -2.]]



In [44]:
# 배열의 형 변환 ***
print(z2); print()
print(z2.flatten()) # 평탄화 시킴 : 모든 차수의 배열을 1차원으로

[[ 5.]
 [10.]
 [15.]]

[ 5. 10. 15.]


In [49]:
# array인덱싱, 슬라이싱, 반복
a = np.arange(10)**2
print(a)
print(a[3:5])
print(a[2])
print(a[::-1])
print(a[0:6:2])
a[0:6:2] = -a[0:6:2]
print(a)

[ 0  1  4  9 16 25 36 49 64 81]
[ 9 16]
4
[81 64 49 36 25 16  9  4  1  0]
[ 0  4 16]
[  0   1  -4   9 -16  25  36  49  64  81]


In [51]:
# 반복문
for x in a:
    print(x+1, end=' ')

1 2 -3 10 -15 26 37 50 65 82 

In [57]:
a = np.arange(1,21,1).reshape(4,5)
print(a); print()
print(a[2,1]); print()
print(a[:2,]); print()
print(a[1,]); print()
print(a[:,-1])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

12

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

[ 6  7  8  9 10]

[ 5 10 15 20]


In [60]:
# numpy의 함수
a = np.arange(1,6,1)
print(a)
print(np.sin(a))
print(np.cos(a))
print(np.log(a))

[1 2 3 4 5]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [62]:
a1 = np.array([10,3,4])
a2 = np.array([4,5,6])
print(np.maximum(a1,a2))
print(np.minimum(a1,a2))
print(np.sum(a1))

[10  5  6]
[4 3 4]
17


In [69]:
print(np.random.choice(100,5)) # 0~100의 숫자 중 5개만 뽑기
print()
print(np.random.rand(2,3)); print()
print(np.random.randn(2,3))

[69 57  6 47 68]

[[0.73395632 0.81110146 0.14125967]
 [0.91688359 0.06467998 0.36756096]]

[[ 0.31933656 -1.18029387  0.66723087]
 [ 2.18817599  0.94723128  0.52492119]]


In [75]:
a = np.array([6,10,3,2,4,5])
print(np.argmax(a)) # 가장 큰 값의 인덱스 반환
print(a[np.argmax(a)])
print(np.argmin(a)) # 가장 작은 값의 인덱스 반환
print(a[np.argmin(a)])
print()

a = np.array([[1,8,2],[3,2,5],[9,5,3]])
print(np.argmax(a,axis=1))

1
10
3
2

[1 2 0]


In [87]:
np.random.seed(0) # 시드값을 넣어주면 매 실행마다 값이 바뀌지 않는다.
print(np.random.rand(5))

[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548 ]


In [3]:
x = np.arange(1,21)
print(x)
print(x[x%3==0])
print(x[x%4==1])
print(x[(x%3==0) & (x%4==1)])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 3  6  9 12 15 18]
[ 1  5  9 13 17]
[9]
