In [2]:
# 데이터 표준환
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('./dataset/auto-mpg.csv',header=None)
df.columns = ['mpg','cylinders','displacement','horsepower','weight',
             'acceleration','model year','origin','name']

In [4]:
# 단위 환산

# mpg = mile per gallon
# kpl = kilometer per liter
# mpg -> kpl
mpg_to_kpl = 1.60934/3.78541
df['kpl'] = df['mpg']*mpg_to_kpl

# 소수점 2자리 미만에서 반올림
df['kpl'] = df['kpl'].round(2)
df.head()

mpg  cylinders  displacement horsepower  weight  acceleration  model year  \
0  18.0          8         307.0      130.0  3504.0          12.0          70   
1  15.0          8         350.0      165.0  3693.0          11.5          70   
2  18.0          8         318.0      150.0  3436.0          11.0          70   
3  16.0          8         304.0      150.0  3433.0          12.0          70   
4  17.0          8         302.0      140.0  3449.0          10.5          70   

   origin                       name   kpl  
0       1  chevrolet chevelle malibu  7.65  
1       1          buick skylark 320  6.38  
2       1         plymouth satellite  7.65  
3       1              amc rebel sst  6.80  
4       1                ford torino  7.23

In [5]:
# 자료형 변환
print(df.dtypes); print()
print(df['horsepower']); print()
print(df['horsepower'].unique()) # 데이터의 값 중복없이 하나씩만 출력

# df['horsepower'] = df['horsepower'].astype('float')
# ValueError: could not convert string to float: '?'
# '?' 문자를 처리해야 함.
# 1. 특수문자 -> NaN으로 치환
# 2. NaN 데이터 행을 삭제
# 3. 데이터의 형을 변환

mpg             float64
cylinders         int64
displacement    float64
horsepower       object
weight          float64
acceleration    float64
model year        int64
origin            int64
name             object
kpl             float64
dtype: object

0      130.0
1      165.0
2      150.0
3      150.0
4      140.0
       ...  
393    86.00
394    52.00
395    84.00
396    79.00
397    82.00
Name: horsepower, Length: 398, dtype: object

['130.0' '165.0' '150.0' '140.0' '198.0' '220.0' '215.0' '225.0' '190.0'
 '170.0' '160.0' '95.00' '97.00' '85.00' '88.00' '46.00' '87.00' '90.00'
 '113.0' '200.0' '210.0' '193.0' '?' '100.0' '105.0' '175.0' '153.0'
 '180.0' '110.0' '72.00' '86.00' '70.00' '76.00' '65.00' '69.00' '60.00'
 '80.00' '54.00' '208.0' '155.0' '112.0' '92.00' '145.0' '137.0' '158.0'
 '167.0' '94.00' '107.0' '230.0' '49.00' '75.00' '91.00' '122.0' '67.00'
 '83.00' '78.00' '52.00' '61.00' '93.00' '148.0' '129.0' '96.00' '71.00'
 '98.00' '115.0' '53.00' '81.00' '79.00' '120.0' 

In [6]:
# 1. '?' -> numpy.nan으로 대체 .replace(바꿀값, 대체할 값, inplace=True)
df['horsepower'].replace('?',np.nan,inplace=True)
print(df['horsepower'].unique())

['130.0' '165.0' '150.0' '140.0' '198.0' '220.0' '215.0' '225.0' '190.0'
 '170.0' '160.0' '95.00' '97.00' '85.00' '88.00' '46.00' '87.00' '90.00'
 '113.0' '200.0' '210.0' '193.0' nan '100.0' '105.0' '175.0' '153.0'
 '180.0' '110.0' '72.00' '86.00' '70.00' '76.00' '65.00' '69.00' '60.00'
 '80.00' '54.00' '208.0' '155.0' '112.0' '92.00' '145.0' '137.0' '158.0'
 '167.0' '94.00' '107.0' '230.0' '49.00' '75.00' '91.00' '122.0' '67.00'
 '83.00' '78.00' '52.00' '61.00' '93.00' '148.0' '129.0' '96.00' '71.00'
 '98.00' '115.0' '53.00' '81.00' '79.00' '120.0' '152.0' '102.0' '108.0'
 '68.00' '58.00' '149.0' '89.00' '63.00' '48.00' '66.00' '139.0' '103.0'
 '125.0' '133.0' '138.0' '135.0' '142.0' '77.00' '62.00' '132.0' '84.00'
 '64.00' '74.00' '116.0' '82.00']


In [7]:
# 2. NaN 데이터 행을 삭제
df.dropna(subset=['horsepower'],axis=0,inplace=True)
print(df['horsepower'].unique())

['130.0' '165.0' '150.0' '140.0' '198.0' '220.0' '215.0' '225.0' '190.0'
 '170.0' '160.0' '95.00' '97.00' '85.00' '88.00' '46.00' '87.00' '90.00'
 '113.0' '200.0' '210.0' '193.0' '100.0' '105.0' '175.0' '153.0' '180.0'
 '110.0' '72.00' '86.00' '70.00' '76.00' '65.00' '69.00' '60.00' '80.00'
 '54.00' '208.0' '155.0' '112.0' '92.00' '145.0' '137.0' '158.0' '167.0'
 '94.00' '107.0' '230.0' '49.00' '75.00' '91.00' '122.0' '67.00' '83.00'
 '78.00' '52.00' '61.00' '93.00' '148.0' '129.0' '96.00' '71.00' '98.00'
 '115.0' '53.00' '81.00' '79.00' '120.0' '152.0' '102.0' '108.0' '68.00'
 '58.00' '149.0' '89.00' '63.00' '48.00' '66.00' '139.0' '103.0' '125.0'
 '133.0' '138.0' '135.0' '142.0' '77.00' '62.00' '132.0' '84.00' '64.00'
 '74.00' '116.0' '82.00']


In [8]:
# 3. 데이터타입을 'object' -> 'float'
df['horsepower'] = df['horsepower'].astype('float')
print(df['horsepower'].dtypes)

float64


In [9]:
# 여러 종류의 값 변경
print(df['origin'].unique())

[1 3 2]


In [10]:
df['origin'].replace({1:'USA',2:'EU',3:'JPN'},inplace=True)
print(df['origin'].unique())
print(df['origin'].dtypes)

['USA' 'JPN' 'EU']
object


In [11]:
# 문자열을 범주형으로 변환
df['origin'] = df['origin'].astype('category')
print(df['origin'].unique()); print()
print(df['origin'].dtypes)

['USA', 'JPN', 'EU']
Categories (3, object): ['EU', 'JPN', 'USA']

category


In [12]:
# 범주형을 문자형으로 변환
df['origin'] = df['origin'].astype('str')
print(df['origin'].unique()); print()
print(df['origin'].dtypes)

['USA' 'JPN' 'EU']

object


In [13]:
# 'model year'의 데이터타입을 확인해보고 범주형으로 형 변환
print(df['model year'].dtypes); print()
print(df['model year'].head()); print()
df['model year'] = df['model year'].astype('category')
print(df['model year'].unique())

int64

0    70
1    70
2    70
3    70
4    70
Name: model year, dtype: int64

[70, 71, 72, 73, 74, ..., 78, 79, 80, 81, 82]
Length: 13
Categories (13, int64): [70, 71, 72, 73, ..., 79, 80, 81, 82]


In [14]:
# 구간 분할 binning
# np.histogram() 함수를 활용하여 각 구간의 경계선 구하기
count, bin_dividers = np.histogram(df['horsepower'], bins=3)
print(count, # 각 구간별 값의 갯수
      bin_dividers) # 구간 경계값
print()

# pd.cut() 함수로 데이터를 3개의 구역에 할당
bin_names = ['저출력','보통출력','고출력']
df['hp_bin'] = pd.cut( x=df['horsepower'], # 데이터
                     bins = bin_dividers, # 경계값 리스트
                     labels = bin_names, # 구역의 이름
                     include_lowest = True # 각 구간의 낮은 경계값 포함 여부
                     )
print(df[['horsepower','hp_bin']].head(15)); print()
print(df.hp_bin.unique()); print()
print(df['hp_bin'].value_counts())

[257 103  32] [ 46.         107.33333333 168.66666667 230.        ]

    horsepower hp_bin
0        130.0   보통출력
1        165.0   보통출력
2        150.0   보통출력
3        150.0   보통출력
4        140.0   보통출력
5        198.0    고출력
6        220.0    고출력
7        215.0    고출력
8        225.0    고출력
9        190.0    고출력
10       170.0    고출력
11       160.0   보통출력
12       150.0   보통출력
13       225.0    고출력
14        95.0    저출력

['보통출력', '고출력', '저출력']
Categories (3, object): ['저출력' < '보통출력' < '고출력']

저출력     257
보통출력    103
고출력      32
Name: hp_bin, dtype: int64


In [15]:
# 컴퓨터가 인식 가능한 값(더미값;dummy)으로 변경하기
hp_dummies = pd.get_dummies(df['hp_bin'])
hp_dummies.head(15)

저출력  보통출력  고출력
0     0     1    0
1     0     1    0
2     0     1    0
3     0     1    0
4     0     1    0
5     0     0    1
6     0     0    1
7     0     0    1
8     0     0    1
9     0     0    1
10    0     0    1
11    0     1    0
12    0     1    0
13    0     0    1
14    1     0    0

In [16]:
# 머신러닝 분석을 위한 라이브러리
from sklearn import preprocessing # 전처리 모듈
# 전처리를 위한 인코더 encoder
label_encoder = preprocessing.LabelEncoder() # LabelEncoder 인스턴스 생성
onehot_encoder = preprocessing.OneHotEncoder() # onehot encoder 생성

# label encoder로 문자형 범주를 숫자형 범주로 변환
onehot_labeled = label_encoder.fit_transform(df['hp_bin'].head(15))
print(onehot_labeled)
# 저출력 2 보통출력 1 고출력 0 -> 가나다순

# 2차원 배열로 변경
onehot_reshaped = onehot_labeled.reshape(len(onehot_labeled),1)
print(onehot_reshaped)

# 희소행렬로 변환
onehot_fitted = onehot_encoder.fit_transform(onehot_reshaped)
print(onehot_fitted)
print(type(onehot_fitted))

[1 1 1 1 1 0 0 0 0 0 0 1 1 0 2]
[[1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [2]]
  (0, 1)	1.0
  (1, 1)	1.0
  (2, 1)	1.0
  (3, 1)	1.0
  (4, 1)	1.0
  (5, 0)	1.0
  (6, 0)	1.0
  (7, 0)	1.0
  (8, 0)	1.0
  (9, 0)	1.0
  (10, 0)	1.0
  (11, 1)	1.0
  (12, 1)	1.0
  (13, 0)	1.0
  (14, 2)	1.0
<class 'scipy.sparse.csr.csr_matrix'>


In [19]:
country = pd.DataFrame({'country':['usa','brazil','maxico','france','spain','china','japan','korea']})
country

country
0     usa
1  brazil
2  maxico
3  france
4   spain
5   china
6   japan
7   korea

In [27]:

country['continent'] = country['country'].replace(['usa','brazil','maxico'],'america')
country

country continent
0     usa   america
1  brazil   america
2  maxico   america
3  france    france
4   spain     spain
5   china     china
6   japan     japan
7   korea     korea